import type { NextPage } from 'next'
import Head from 'next/head'
import HelloWorld from '@components/HelloWorld/HelloWorld';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HelloWorld />
      </main>

    </div>
  )
}

export default Home
